### ISSUE TITLE
Unable to parse scalar return type declarations

### ISSUE THREAD

**Issue by SorryAmNoJustinBieber** [phpDocumentor/phpDocumentor2#2020] opened 2018-09-17 23:03 UTC
`v3.0.0-alpha.2-nightly-gdff5545/phpDocumentor.phar` is unable to parse scalar return type declarations in interfaces and traits, I suspect the behaviour is the same in classes but haven't had the time to test it.

`interface IMyInterface {
  public function MyFunction( ) : bool;
}`

`trait TMyTrait {
  public function MyFunction( ) : IMyInterface {
    return $this;
  }
}`

The parse error will say smth amongst the lines of `unexpected : expected ;`

Not much more to be said..

**Comment by mvriel** [comment] 2018-09-23 14:01
I have tried to reproduce this using the latest version on develop and it seems to be fixed in the mean time. There is a new phar file available on the releases page; can you retry using that? Thanks for reporting this

**Comment by SorryAmNoJustinBieber** [comment] 2018-09-23 16:41
Am unable to call `run` in newest versions tried phar and tar.gz. 

>>
CODASYL@LOCAL003:/var/www/html$ sudo php phpDocumentor.phar run -d /var/www/html/Release/ -t /var/www/html/OutX
[2018-09-23 18:33:37] app.INFO: Elapsed time to parse all files: 0s [] []
[2018-09-23 18:33:37] app.INFO: Peak memory usage: 20M [] []
[2018-09-23 18:33:37] console.ERROR: Error thrown while running command "run -d '/var/www/html/Release/' -t '/var/www/html/OutX'". Message: "Argument 2 passed to phpDocumentor\Compiler\Pass\PackageTreeBuilder::createPackageDescriptorTree() must be of the type string, object given, called in phar:///var/www/html/phpDocumentor.phar/src/phpDocumentor/Compiler/Pass/PackageTreeBuilder.php on line 96" {"exception":"[object] (TypeError(code: 0): Argument 2 passed to phpDocumentor\\Compiler\\Pass\\PackageTreeBuilder::createPackageDescriptorTree() must be of the type string, object given, called in phar:///var/www/html/phpDocumentor.phar/src/phpDocumentor/Compiler/Pass/PackageTreeBuilder.php on line 96 at phar:///var/www/html/phpDocumentor.phar/src/phpDocumentor/Compiler/Pass/PackageTreeBuilder.php:131)","command":"run -d '/var/www/html/Release/' -t '/var/www/html/OutX'","message":"Argument 2 passed to phpDocumentor\\Compiler\\Pass\\PackageTreeBuilder::createPackageDescriptorTree() must be of the type string, object given, called in phar:///var/www/html/phpDocumentor.phar/src/phpDocumentor/Compiler/Pass/PackageTreeBuilder.php on line 96"} []
[2018-09-23 18:33:37] console.ERROR: Error thrown while running command "{command}". Message: "{message}" {"exception":"[object] (TypeError(code: 0): Argument 2 passed to phpDocumentor\\Compiler\\Pass\\PackageTreeBuilder::createPackageDescriptorTree() must be of the type string, object given, called in phar:///var/www/html/phpDocumentor.phar/src/phpDocumentor/Compiler/Pass/PackageTreeBuilder.php on line 96 at phar:///var/www/html/phpDocumentor.phar/src/phpDocumentor/Compiler/Pass/PackageTreeBuilder.php:131)","command":"run -d '/var/www/html/Release/' -t '/var/www/html/OutX'","message":"Argument 2 passed to phpDocumentor\\Compiler\\Pass\\PackageTreeBuilder::createPackageDescriptorTree() must be of the type string, object given, called in phar:///var/www/html/phpDocumentor.phar/src/phpDocumentor/Compiler/Pass/PackageTreeBuilder.php on line 96"} []

In PackageTreeBuilder.php line 131:

  Argument 2 passed to phpDocumentor\Compiler\Pass\PackageTreeBuilder::createPackageDescriptorTree() must be of the type string, object given, called in phar:///var/www/html/phpDocumentor.ph
  ar/src/phpDocumentor/Compiler/Pass/PackageTreeBuilder.php on line 96

**Comment by jaapio** [comment] 2018-09-23 16:45
Thanks for your feedback. We will investigate this new issue.

**Comment by jaapio** [comment] 2018-10-21 07:03
We released a new phar yesterday. In which the issue reported by you is fixed. Please let us know if you have any problems running the new release.

**Comment by jaapio** [comment] 2018-12-31 13:00
Closing because this should be fixed. No response from the original author. 
Feel free to open a new issue when needed.

**Closed by jaapio** 2018-12-31 13:00 UTC
Labels: ready
