### ISSUE TITLE
Support for Generator/yield

### ISSUE THREAD

**Issue by wizacedric** [phpDocumentor/phpDocumentor2#2012] opened 2018-08-23 15:25 UTC
PhpDocumentor should support Generators.

## Expected Behavior
PhpDocumentor should provide a `@yield` tag. That tag would describe the type of data yielded by the Generator.

## Actual Behavior
PhpDocumentor does not support Generators and does not provide a `@yield` tag.

## Steps to resolution
I can work on a PR if that proposed tag is Ok with you.

**Comment by asmundstavdahl** [comment] 2018-09-01 22:34
My two cents: @throws, @uses, @yields?

**Comment by asmundstavdahl** [comment] 2018-09-04 06:46
I guess.

jsdoc3 solves it by making [return a synonym for returns](https://github.com/jsdoc3/jsdoc3.github.com/blob/master/content/en/tags-returns.md) and doing the same for yield.

**Comment by jaapio** [comment] 2018-10-12 20:14
I mark this as a duplicate of https://github.com/phpDocumentor/fig-standards/issues/5. Lets continue the discussion there. We will be psr-5 compatible. But won't introduce any new tags when the are not standardized at this moment.

**Closed by jaapio** 2018-10-12 20:14 UTC
Labels: RFC
