### ISSUE TITLE
Error on Windows Install with pear

### ISSUE THREAD

**Issue by RodriAndreotti** [phpDocumentor/phpDocumentor2#1579] opened 2015-05-29 17:15 UTC
Aways when I try to install phpDocumentor 2.8.2 on windows I receive the message: ERROR: unable to unpack, even when I use the argument --nocompress.

- Installing on the linux with pear Works fine
- Installing the version 2.8.1 on windows works fine

My PHP version is 5.6

![phpdoc](https://cloud.githubusercontent.com/assets/9449048/7888109/7a053f0c-060c-11e5-9945-564f58dde627.png)

Another packages are installed succesfully.

Thanks.

**Comment by TomasVotruba** [comment] 2015-05-29 17:36
@RodriAndreotti It might be caused by the spaces in "Ambiente de des...". Try to install project in directory without spaces.

**Comment by RodriAndreotti** [comment] 2015-05-29 18:13
Hi @TomasVotruba,

Thanks,

I thought it might be something about it. I just thought it strange that the previous version installed without problems

**Comment by TomasVotruba** [comment] 2015-05-29 18:32
@RodriAndreotti Have you managed to install successfully?

**Comment by RodriAndreotti** [comment] 2015-05-29 18:43
Yes... the previous version (2.8.1) install without problems.
But the 2.8.2 won't install

**Comment by TomasVotruba** [comment] 2015-05-29 18:50
@RodriAndreotti Even after my suggestion?

**Comment by RodriAndreotti** [comment] 2015-05-29 18:51
I don't have tested yet, I will do this now.

**Comment by TomasVotruba** [comment] 2015-05-29 19:03
@RodriAndreotti :+1:

**Comment by mvriel** [comment] 2015-12-02 17:37
This might also be a duplicate of https://github.com/phpDocumentor/phpDocumentor2/issues/1544; where a file in the package has a colon (`:`), causing issues on windows

**Comment by rgeraads** [comment] 2015-12-06 20:48
I have a feeling this might have been fixed by #1568.
@RodriAndreotti could you check if the problem still occurs?

**Comment by RodriAndreotti** [comment] 2015-12-07 13:47
Well, on my development machine won't works, see attached file:
![erro_phpdoc](https://cloud.githubusercontent.com/assets/9449048/11628287/da4480a0-9cd7-11e5-9634-acfffcd1a1ea.png)

I have tried to install on a VM, but the pear documentation sites are offline, and go-pea.phar and pyrus.phar links are inside docs.

In this VM the path to php dir is C;\dev\php, I want to try on this vm because have no space in the path.

**Closed** 2016-05-22 19:40 UTC
Labels: Blocking, Bug, ready
