### ISSUE TITLE
Several extensions are not listed in composer requirements

### ISSUE THREAD

**Issue by dktapps** [phpDocumentor/phpDocumentor2#2054] opened 2019-01-06 11:33 UTC
When installing phpDocumentor2 using Composer, everything seems to be fine until trying to run it.
My PHP build is stripped-back (built with `--disable-all` and only specific extensions enabled to reduce build size), and does not have several extensions that phpDocumentor expects to be present but does not declare in `composer.json`.

According to a PhpStorm scan of the project on the `develop` branch, the missing dependencies are:
- `ext-dom`
- `ext-simplexml`
- `ext-libxml`
- `ext-xsl`
- `ext-zlib`

There may be other dependencies on other branches that I have not checked.

## Expected Behavior
Installing `phpDocumentor2` with my PHP setup should fail because `ext-dom`, `ext-simplexml` and `ext-libxml` are not found in my PHP build

## Actual Behavior
phpDocumentor2 installs successfully and crashes when trying to run.

## Steps to Reproduce the Problem
  1. Compile PHP with any of the listed XML extensions missing (`simplexml` is the first problem I encountered)
  2. Install phpDocumentor in a project
  3. Try to generate documentation and watch it crash.

## Your environment
* Version used: 2.9
* Install method: `composer install phpdocumentor/phpdocumentor`
* php version: 7.2.13
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10

**Comment by jaapio** [comment] 2019-01-07 18:38
Thanks for your report, we are working currently on a new version of phpdocumentor, which does have the listed requirements. 
Due limited time we don't give this issue priority over the new version.

**Comment by mvriel** [comment] 2019-06-15 20:21
While reviewing this issue and the composer.json of v3 I noticed some of your suggestions were missing. I have resolved this for v3, because of limited resources we are not able to backport many of these improvements to v2.x. Because of this limitation, I am going to close this item as the issue is resolved in v3.

If you have more suggestions like these we would love to hear more!

**Closed by mvriel** 2019-06-15 20:21 UTC
Labels: help wanted
