### ISSUE TITLE
phpdoc.xml and phpdoc.dist.xml shouldn't be mandatory

### ISSUE THREAD

**Issue by neoascetic** [phpDocumentor/phpDocumentor2#1778] opened 2016-07-12 11:15 UTC

**Comment by mvriel** [comment] 2017-05-19 10:30
Unfortunately, I do not understand what the expected behaviour should be; the configuration files are not mandatory and phpDocumentor can be run without them but then you must specify a folder to parse using the `-d` or `-f` parameter.

I verified this using the following test when I am in the folder of a project that doesn't feature a configuration file for phpDocumentor:

``` bash
$ curl -O https://phpdoc.org/phpDocumentor.phar
$ chmod +x phpDocumentor.phar
$ ./phpDocumentor.phar -d src/
```
The documentation is generated for the `src` folder and then stored in the `output` folder.

Since the issue is not clear and I was unable to discover why I will be closing this issue; should you want to provide more information: please comment on this issue and I will reopen it

**Closed by mvriel** 2017-05-19 10:30 UTC
