### ISSUE TITLE
0 errors (php documentor version 3) but they should be

### ISSUE THREAD

**Issue by in4s** [phpDocumentor/phpDocumentor2#2032] opened 2018-11-04 21:21 UTC
phpdoc v2 gave me some list of errors in docummentation (and that's right)
phpdoc v3 gave me 0 errors (number of markers is correct 59 in my case)
I ran it from phar version with the command "php ../phpDocumentor.phar run -t public/phpdocs/ -d vendor/j4s/base/"
## Expected Behavior

I want to see my 5 errors.

## Actual Behavior

phpdoc v3 gave me 0 errors (number of markers is correct 59 in my case)

## Steps to Reproduce the Problem
Should I send you my files?

## Your environment

* Version used: Release v3.0.0-alpha.3
* Install method phar
* php version 7.2.10

**Comment by jaapio** [comment] 2018-11-05 07:30
Validation was removed in phpdoc v3. Because it returned to many errors, and validation is more a coding style thing. We want to reintroduce validation in a later stadum. But currently it isn't in.

**Comment by insolution4** [comment] 2018-11-05 07:58
IMHO it is very helpful. In my code It shows only 1-2 strange error types but in general errors is very helpful for me. It's a roadmap for correct docummenting. Could not you make it optional? I am really need it.

**Comment by joshmbg** [comment] 2019-02-19 16:10
In that case, you should remove the validation option. It is very annoying having a flag there that does nothing, and leaves users like us spending time trying to figure out why it isn't working.

For the record: Validation is very useful; please add it back in. I have far too many files (406) in my project to check them all manually, and having the validation would be very helpful.

**Comment by mvriel** [comment] 2019-06-15 21:06
Validation is definitely going to be re-implemented; unfortunately due to some changes it is not as trivial as we would like to see.

This project (https://github.com/phpDocumentor/phpDocumentor2/projects/6) contains a preliminary list of activities and is something which you can use to track progress.

For now, I am going to close the issue since it is a duplicate of a whole project; let's continue there! :)

**Closed by mvriel** 2019-06-15 21:06 UTC
Labels: RFC
