### ISSUE TITLE
Class constant called "NAMESPACE" causes class to vanish from docs

### ISSUE THREAD

**Issue by Veraxus** [phpDocumentor/phpDocumentor2#2017] opened 2018-09-07 02:58 UTC
I have a project where a class has a constant of NAMESPACE. If the NAMESPACE constant is declared **_or_** used in any class or method of a class, the entire class disappears from the generated documentation.

Would cause a class to disappear:

`const NAMESPACE = 'this-is-a-namespace'`

As a clue, the following would also cause the MyClass class to not appear in documentation even if const NAMESPACE isn't defined in the class...
`
class MyClass
{
    public function myFunction()
    {
        return self::NAMESPACE
    }
}
`
However, `const PREFIX_NAMESPACE` does not have this issue.

## Expected Behavior
A constant named NAMESPACE should appear as a constant in documentation and should not cause a class to disappear from generated documentation.

## Actual Behavior
When a class contains a constant (or reference to a constant) named NAMESPACE, the entire class disappears from all documentation (other than Error Reports)

## Steps to Reproduce the Problem

  1. Create a class
  2. Do either:
     * Declare a constant called NAMESPACE or
     * Create a function, and reference a constant called NAMESPACE
  3. Run PhpDoc

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 3.0.0-alpha1
* Install method - Composer
* php version 7.1.19
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): MacOS 10.13.6
* Link to your project: https://github.com/Veraxus/nouveau/blob/1.0-wip/NV/Admin/Gutenberg.php#L25

**Comment by mvriel** [comment] 2018-09-23 17:59
Looking into this

**Comment by mvriel** [comment] 2018-09-23 18:10
This issue seems to be resolved in the latest version of phpDocumentor on the develop branch. I have used the following test file and was unable to reproduce the issue:

```
<?php

namespace Abc;

class Abc {
    const NAMESPACE = 'this-is-a-namespace';
}
```

With this file content I have generated the documentation using the following command:

> ./bin/phpdoc -f test.php

And when I open the output then I can see the class and the namespace with the value that I declared above. This is verified on PHP 7.2.0.

Are you able to verify whether this issue still persists in the latest version on develop? We have made many fixes since the last phar and it could be resolved in the mean time.

**Closed** 2019-06-15 21:04 UTC
Labels: needs author update
