### ISSUE TITLE
@version and @since is not working.

### ISSUE THREAD

**Issue by ve3** [phpDocumentor/phpDocumentor2#1843] opened 2017-04-30 06:19 UTC
```
<?php
/**
 * File level document.
 * 
 * @license http://opensource.org/licenses/MIT MIT
 */


namespace Modules\Home\Libraries;


/**
 * Test class that will be generate API document.
 * This class has no any real functional.
 * 
 * The above text should have 2 lines.<br>
 * This should have 2 lines too.
 * 
 * This is inline code `echo 'The echo here should display in the inline code.';`.<br>
 * This is using inline code (&lt;code&gt;) but what result it is: <code>echo 'The echo in the code html.';</code>.<br>
 * The code below is in pre element (&lt;pre&gt;).
 * <pre>
 * $Class = new Class();
 * $Class->property;
 * $Class->method();
 * unset($Class);
 * </pre>
 *
 * @author Vee W.
 * @package Test API doc
 * @version 1.1
 * @since 1.0
 */
class TestLib
{


    /**
     * The class constructor.
     * 
     * @todo Example to do.
     */
    public function __construct()
    {
        
    }// __construct


    /**
     * This is the public function and it should be generated into API doc.
     * 
     * @param array $data The array data.
     * @param mixed $args Optional arguments.
     * @return mixed Return various data types.
     */
    public function publicFunction(array $data, $args = null)
    {
        $this->anotherPublicButProtectedAccess();
    }// publicFunction


    /**
     * This is another public function but it contain protected access doc.
     * 
     * @access protected Do not access this directly.
     * @deprecated 1.1 Deprecated, will be remove in v.999
     * @param array $data The array data.
     */
    public function anotherPublicButProtectedAccess(array $data)
    {
        
    }// anotherPublicButProtectedAccess


    /**
     * This is real protected function but it is still should be generated into API doc.
     * 
     * @param array $data The array data.
     * @param type $args Optional arguments.
     * @return mixed Return various data types.
     */
    protected function protectedFunction(array $data, $args = null)
    {
        
    }// protectedFunction


    /**
     * This is private function and should not be generated into API doc.
     * 
     * @param array $data The array data.
     * @param type $args Optional arguments.
     * @return mixed Return various data types.
     */
    private function privateFunction(array $data, $args = null)
    {
        
    }// privateFunction


}
```

![phpdocumentor version and since not working](https://cloud.githubusercontent.com/assets/1568262/25562145/7745a652-2da7-11e7-8984-de0296355778.jpg)

Both `@version 1.1` and `@since 1.0` are not showing.
phpDocumentor v 2.9.0

**Comment by jaapio** [comment] 2017-04-30 07:02
Can you try another template? I know there are some issues with templates regarding these tags

**Comment by ve3** [comment] 2017-04-30 07:12
add --template="..." to the command...
`clean` => not working (as seen in the screenshot).
`responsive-twig` => works, `@version` and `@since` is showing.
`responsive` => error!
`checkstyle` => template not found!
`new-black` => error!
`zend` => error!
`abstract` => error!

**Comment by jaapio** [comment] 2017-04-30 07:12
Thanks for trying, we will get back to you

**Comment by mvriel** [comment] 2017-05-19 07:01
@ve3 I have just tried to reproduce your issue using phpDocumentor v2.9.0 and could not reproduce this; have you upgraded to the latest version?
<img width="1055" alt="screen shot 2017-05-19 at 09 00 24" src="https://cloud.githubusercontent.com/assets/193704/26236649/bd59f35e-3c71-11e7-9eea-4c1221423a29.png">

**Comment by mvriel** [comment] 2017-05-19 11:42
I just verified; this issue was resolved last year on master. I will close this issue as no more effort is needed

**Closed by mvriel** 2017-05-19 11:42 UTC

**Comment by ve3** [comment] 2017-05-19 11:45
Yes, I am using 2.9.0 is it latest version?

**Comment by mvriel** [comment] 2017-05-19 12:06
2.9.0 is the latest released version; the fix is currently available on master and will be included in the next release
