### ISSUE TITLE
Ability to specify Twig cache directory

### ISSUE THREAD

**Issue by cezarykluczynski** [phpDocumentor/phpDocumentor2#1605] opened 2015-07-06 18:58 UTC
I would like to request a configurable Twig cache directory.

From what I understand, it's around here:

https://github.com/phpDocumentor/phpDocumentor2/blob/28441646799aee8dfe1d4cf41b670831fd59558f/src/phpDocumentor/Plugin/Twig/Writer/Twig.php#L145

that the Twig is initialized and the cache directory is set to the system directory.

However, I would like to have the ability to store Twig cache not higher than the project root directory, and certainly not in shared /tmp folder.

Would you consider adding this feature? If so, would a pull request be considered? If so, how would you approach the problem? A XML config example and a CLI param name would be enough to get me started.

I would go with something like

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdoc>
  <twig>
    <cache_folder>tmp/twig/cache</cache_folder>
  </twig>
</phpdoc>
```

And CLI:

``` sh
vendor/bin/phpdoc --twig-cache-folder="tmp/twig/cache"
```

I assume folder should be created if it does not exist.

**Comment by papriwalprateek** [comment] 2016-09-20 04:37
Is there any update on this issue?

**Comment by wrlee** [comment] 2018-01-02 21:29
**Use case:** I am on a shared server, so if any user on the server creates a `/tmp/phpdoc-twig-cache` , no one else can run phpdoc since access to the hard-coded directory is prevented by another user.

**Comment by jaapio** [comment] 2018-01-03 08:17
Will be part of v3.0.0-alpha2

**Comment by rmccue** [comment] 2018-08-09 02:29
This would be super useful. We're looking at setting up phpDoc-as-a-service, so it would improve performance a bunch if we could pre-compile the Twig templates and point phpDocumentor to it.

**Comment by mvriel** [comment] 2018-09-03 06:46
I am picking this up

**Comment by mvriel** [comment] 2018-09-04 15:48
This issue has been resolved by caching the twig files in the project's cache directory that is configurable in your phpdoc.xml. This will ensure that the cache is not shared between projects and is hence decoupled.

Please note that we have chosen not to make this configurable in addition to the project cache location to keep it simple (one cache location for all caches) and because it would require a significant investment, at the moment, to have plugins (such as the Twig plugin) have their own bits of configuration.

Even though this latter option is desirable I have chosen to postpone that for now and ensure that this feature is delivered now to you.

**Comment by mvriel** [comment] 2018-09-04 15:48
I am closing this as the issue is resolved in develop; I will reopen it if comments indicate that a followup is needed.

**Closed by mvriel** 2018-09-04 15:48 UTC
Labels: Improvement

**Comment by rmccue** [comment] 2018-09-05 00:49
This is great thanks! We can always handle configuration by manually messing with the cache directory. :)
