### ISSUE TITLE
 Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName()

### ISSUE THREAD

**Issue by BronislavKlucka** [phpDocumentor/phpDocumentor2#2073] opened 2019-03-15 14:52 UTC
PHP Documentor generates message in title when parsing file

## Expected Behavior
generate documentation

## Actual Behavior
 /www/hermes/phpDocumentor.phar -t /www/hermes/profisms.cz/hermesdoc.profisms.cz -f /www/hermes/common/message/messagestate.class.php
[2019-03-15 15:47:09] app.INFO: Elapsed time to parse all files: 0s [] []
[2019-03-15 15:47:09] app.INFO: Peak memory usage: 22M [] []
[2019-03-15 15:47:09] app.INFO:  Applying 17 transformations [] []
[2019-03-15 15:47:09] app.INFO:   Initialize writer "phpDocumentor\Plugin\Core\Transformer\Writer\FileIo" [] []
[2019-03-15 15:47:09] app.INFO:   Initialize writer "phpDocumentor\Plugin\Twig\Writer\Twig" [] []
[2019-03-15 15:47:09] app.INFO:   Initialize writer "phpDocumentor\Plugin\Graphs\Writer\Graph" [] []
[2019-03-15 15:47:09] app.INFO:   Writer FileIo  using query "copy" on .htaccess [] []
[2019-03-15 15:47:09] app.INFO:   Execute transformation using writer "FileIo" [] []
[2019-03-15 15:47:09] app.INFO:   Writer FileIo  using query "copy" on images [] []
[2019-03-15 15:47:09] app.INFO:   Execute transformation using writer "FileIo" [] []
[2019-03-15 15:47:09] app.INFO:   Writer FileIo  using query "copy" on css [] []
[2019-03-15 15:47:09] app.INFO:   Execute transformation using writer "FileIo" [] []
[2019-03-15 15:47:09] app.INFO:   Writer FileIo  using query "copy" on js [] []
[2019-03-15 15:47:09] app.INFO:   Execute transformation using writer "FileIo" [] []
[2019-03-15 15:47:09] app.INFO:   Writer FileIo  using query "copy" on font [] []
[2019-03-15 15:47:09] app.INFO:   Execute transformation using writer "FileIo" [] []
[2019-03-15 15:47:09] app.INFO:   Writer twig  using query "namespace" on index.html [] []
[2019-03-15 15:47:09] app.INFO:   Execute transformation using writer "twig" [] []
[2019-03-15 15:47:09] app.INFO:   Writer twig  using query "indexes.namespaces" on  [] []
[2019-03-15 15:47:09] app.INFO:   Execute transformation using writer "twig" [] []
[2019-03-15 15:47:09] app.INFO:   Writer twig  using query "indexes.classes" on  [] []
[2019-03-15 15:47:09] app.INFO:   Execute transformation using writer "twig" [] []
[2019-03-15 15:47:09] console.ERROR: Error thrown while running command "-t '/www/hermes/profisms.cz/hermesdoc.profisms.cz' -f '/www/hermes/common/message/messagestate.class.php'". Message: "Call to undefined method phpDocumentor\Descriptor\TagDescriptor::getVariableName()" {"exception":"[object] (Error(code: 0): Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName() at phar:///data/www/hermes/phpDocumentor.phar/src/phpDocumentor/Descriptor/ClassDescriptor.php:297)","command":"-t '/www/hermes/profisms.cz/hermesdoc.profisms.cz' -f '/www/hermes/common/message/messagestate.class.php'","message":"Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName()"} []
[2019-03-15 15:47:09] console.ERROR: Error thrown while running command "{command}". Message: "{message}" {"exception":"[object] (Error(code: 0): Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName() at phar:///data/www/hermes/phpDocumentor.phar/src/phpDocumentor/Descriptor/ClassDescriptor.php:297)","command":"-t '/www/hermes/profisms.cz/hermesdoc.profisms.cz' -f '/www/hermes/common/message/messagestate.class.php'","message":"Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName()"} []

## Steps to Reproduce the Problem

  1. download phar for Release v3.0.0-alpha.3
  2. run it> /www/hermes/phpDocumentor.phar -t /www/hermes/profisms.cz/hermesdoc.profisms.cz -f /www/hermes/common/message/messagestate.class.php

## Your environment

PHP> PHP 7.2.10-0ubuntu0.18.04.1
PHPDoc> Release v3.0.0-alpha.3

The file can be downloaded here>
http://hermes.profisms.cz/messagestate.class.txt

**Comment by BronislavKlucka** [comment] 2019-03-21 09:55
Hello

Is anyone tracking this?

**Comment by restena-sw** [comment] 2019-04-05 12:02
FWIW, I get the same when trying to generate documentation for Github:GEANT/CAT master branch.

**Comment by jaapio** [comment] 2019-04-08 19:42
We need to check if this issue does still exist in the current version in develop. It would be very helpfull if anyone could install phpdocumentor from source in a separate directory and run the provided files. I didn't have time yet to check this.

**Comment by restena-sw** [comment] 2019-04-09 05:58
Using composer, I compiled dev-develop and its numerous dependencies. And indeed:

phpDocumentor vNo version set (parsed as 1.0.0)@

Parsing files
 241/833 [========>-------------------]  28%
Applying transformations (can take a while)
 17/17 [============================] 100%
All done!

The compiled docs look good on first glance.

So, from what I can see, the bug seems to be gone in dev-develop.

Strangely enough though: I ran phpdoc on an empty source directory that contained only itself in vendor/. And there the problem is still there:

swinter@aragorn:~/Development/GitHub/phpDocumentor> ./vendor/bin/phpdoc
phpDocumentor vNo version set (parsed as 1.0.0)@

Parsing files

Applying transformations (can take a while)
  7/17 [===========>----------------]  41%
In ClassDescriptor.php line 285:
                                                                                                                    
  Attempted to call an undefined method named "getVariableName" of class "phpDocumentor\Descriptor\TagDescriptor".  
                                                                                                                    

project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [--parseprivate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config [CONFIG]] [--log [LOG]] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by mvriel** [comment] 2019-06-15 19:46
Unfortunately, I have not been able to pinpoint the exact culprit. Nonetheless, I have just pushed a fix to develop that should prevent this issue from occurring by doing stricter checks in that part of the code and discarding the bits that do not match.

Since the issue seems to have become rare already and with this patch should be solved I am going to close the issue. If the problem still persists despite these changes, please mention it here and we'll reopen the issue.

**Closed by mvriel** 2019-06-15 19:46 UTC
Labels: Bug, help wanted

**Comment by tbuegel** [comment] 2019-07-19 11:24
I have the same issue 

My environment
PHP> PHP Version 7.3.4 
System> Windows 10 AMD64
PHPDoc> Release v3.0.0-alpha.3

Steps to Reproduce the Problem
download phar for Release v3.0.0-alpha.3
download as Test env: phpDocumentor2-develop.zip
create anywhere directory, name it TEST and copy and extract here: phpDocumentor2-develop.zip
name this directory "phpDoc" so you get a path like [path to]\TEST\phpDoc
this will contain several files and folders and a folder with name "src" and subfolder "phpDocumentor" [path to]\TEST\phpDoc\src\phpDocumentor
open this folder and create a new folder named "doku" [path to]\TEST\phpDoc\src\phpDocumentor\doku
now run the following command
php phpDocumentor.phar -d "[path to]\TEST\phpDoc\src\phpDocumentor" -t "[path to]\TEST\phpDoc\src\phpDocumentor\doku"

Output
[2019-07-19 12:57:41] app.INFO: Starting to parse file: Application/PipelineFactory.php [] []
...
... several lines of output seems to be ok
...
[2019-07-19 12:59:00] app.INFO:   Execute transformation using writer "twig" [] []
[2019-07-19 12:59:04] console.ERROR: Error thrown while running command "-d "[path to]\TEST\phpDoc\src\phpDocumentor" -t "[path to]\TEST\phpDoc\src\phpDocumentor\doku"". Message: "Call to undefined method phpDocumentor\Descriptor\TagDescriptor::getVariableName()" {"exception":"[object] (Error(code: 0): Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName() at phar://[path to]/phpDoc/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/ClassDescriptor.php:297)","command":"-d \"[path to]\\TEST\\phpDoc\\src\\phpDocumentor\" -t \"[path to]\\TEST\\phpDoc\\src\\phpDocumentor\\doku\"","message":"Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName()"} []
[2019-07-19 12:59:04] console.ERROR: Error thrown while running command "{command}". Message: "{message}" {"exception":"[object] (Error(code: 0): Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName() at phar://[path to]/phpDoc/bin/phpDocumentor.phar/src/phpDocumentor/Descriptor/ClassDescriptor.php:297)","command":"-d \"[path to]\\TEST\\phpDoc\\src\\phpDocumentor\" -t \"[path to]\\TEST\\phpDoc\\src\\phpDocumentor\\doku\"","message":"Call to undefined method phpDocumentor\\Descriptor\\TagDescriptor::getVariableName()"} []

In ClassDescriptor.php line 297:

  Attempted to call an undefined method named "getVariableName" of class "phpDocumentor\Descriptor\TagDescriptor".
