### ISSUE TITLE
[3-dev] Is not generating methods documentation

### ISSUE THREAD

**Issue by nelson6e65** [phpDocumentor/phpDocumentor2#2056] opened 2019-01-13 17:15 UTC
## Expected Behavior
Generate all my documentation

## Actual Behavior
Only generates properties documentation

## Steps to Reproduce the Problem

  1. Run  `phpdoc` in my project dir.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 3.0.x-dev d9306e7
* Install method: Composer global
* php version: 7.2.13
* Operating system and version: Fedora 28

## Details

My code, for example [Type.php](https://github.com/nelson6e65/php_nml/blob/14f6bd75fc130f4aec64d9448739e039854e22ab/src/Type.php), has methods in addition to properties, but only generates:

![captura de pantalla de 2019-01-13 13-05-42](https://user-images.githubusercontent.com/9272498/51088289-2fd90200-1734-11e9-802a-4af20e2b8a95.png)

Im using this config:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor>
  <title>PHP: Nelson Martell Library</title>

  <parser>
    <visibility>public,protected</visibility>
    <target>output/doc</target>
  </parser>

  <transformer>
    <target>docs/api</target>
  </transformer>

  <files>
    <directory>src</directory>
    <file>vendor/cakephp/utility/Text.php</file>
  </files>

</phpdocumentor>
```

**Comment by jaapio** [comment] 2019-01-18 20:14
it seems that this issue is caused by the defined visibility. I'm investigating this issue to see how it should be fixed.

**Closed** 2019-01-18 21:18 UTC
