### ISSUE TITLE
Codification for "in/out" (referenced) parameter.

### ISSUE THREAD

**Issue by zeleznypa** [phpDocumentor/phpDocumentor2#2019] opened 2018-09-14 09:20 UTC
Please add codification into the [phpdoc official documentation](http://docs.phpdoc.org/references/phpdoc/tags/param.html), how to [declare "in/out" parameter](https://stackoverflow.com/a/36549165).

For somebody who look at documentation it could be useful to know, that parameter is "in/out".

```php
/**
 * @param string|null &$foo
 */
function foo(?string &foo) {
   //...
}
```

**Comment by ondrejmirtes** [comment] 2018-09-14 09:45
To clarify - this is not a bug, but intended behaviour on PHPStan's side.

**Comment by jaapio** [comment] 2018-09-14 12:49
I don't want to discuss this in the phpdocumentor project. We should first have an agreement on the PSR-5 implementation for this kind of issues before we add any kind of new documentation. Since PSR-5 is any working group which also is supported by the phpstan-team we have to agree both on this. I'm closing this issue because it isn't only up to us to add new docblock syntax. 
Let's continue this discussion in the PSR-5 working group

**Closed by jaapio** 2018-09-14 12:49 UTC
